/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lxzh123_classloader_Helper */

#ifndef _Included_com_lxzh123_classloader_Helper
#define _Included_com_lxzh123_classloader_Helper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lxzh123_classloader_Helper
 * Method:    loadDex
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lxzh123_classloader_Helper_loadDex
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
