/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lxzh123_libshell_Shell */

#ifndef _Included_com_lxzh123_libshell_Jni
#define _Included_com_lxzh123_libshell_Jni
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* reserved);
JNIEXPORT void JNICALL JNI_OnUnload(JavaVM* vm, void* reserved);
///*
// * Class:     com_lxzh123_libshell_Shell
// * Method:    loadDex
// * Signature: ([BJ)I
// */
//JNIEXPORT jint JNICALL Java_com_lxzh123_libshell_Helper_loadDex
//        (JNIEnv *, jclass, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif